apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mysql-db-service.yaml
- db-data-persistentvolumeclaim.yaml
- kustomization.yaml
- node-app-claim2-persistentvolumeclaim.yaml
- notused-persistentvolumeclaim.yaml
- node-app-service.yaml
- mysql-db-deployment.yaml
- node-app-claim0-persistentvolumeclaim.yaml
- boilerplate-network-networkpolicy.yaml
- node-app-deployment.yaml
- node-app-claim1-persistentvolumeclaim.yaml
commonLabels:
  app: tekton-squad-1-node-app
  app.kubernetes.io/instance: tekton-squad-1-node-app-instance
  app.kubernetes.io/name: tekton-squad-1-node-app
images:
- name: node-app
  newName: quay.io/jian_ping_shu/next_js
  newTag: 5916845210f0b838403d574d85d419bb8a3177a3
