apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert -o k8s
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: node-app
  name: node-app
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      Protocol: TCP
  selector:
    io.kompose.service: node-app
status:
  loadBalancer: {}
